name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]   # or 24.x or whatever version you support

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install frontend dependencies
      working-directory: client
      run: npm install

    - name: Compile frontend
      working-directory: client
      run: npm run build

    - name: Install backend dependencies
      working-directory: api
      run: npm install

    - name: Run backend tests
      working-directory: api
      run: npm test    # or any other test command

    # You can add more steps as needed, such as linting, Docker builds, etc.
